### PR TITLE
Major rework of code

### PR DESCRIPTION
**Pull request by rikkimax**
I've moved files around and split them up.
I've changed it to use DerelictUtil and hence part of that family of libraries in loading the external jvm shared library.
It will try to detect the location of the jvm shared library based upon what java -verbose -version responds. its not perfact, but I've based it upon (only x64) Windows and Linux Mint. It should work for you out of the box.

I've changed the DJvm class fairly significantly. It will no longer let you call the constructor directly. There is a limit in the JVM implementation where it is one instance per process.
Your code doesn't need much changes. Its basically ``D DJvm djvm = DJvm.getInstance(); `` instead of creating it.
You can create a new instance but only when no existing instances exist.

There is a testShared subpackage which is an example on how to use the dynamic library called by Java.

At this point it should be fairly easy to wrap Java->D and D->Java.
Java->D can be done by using interfaces as declarations with some mocking.
D->Java will require a mixin template and some way to export java files equivalent. This shouldn't be too hard, will only require a separate program to load the shared library call a method and have all the files exported to the given location.

FYI I have added myself as part of copyright with copyright headers in all source files.

### CODE REVIEW

**Comment by rikkimax** [comment]
Just a little something I've just come up with.
It could be quite useful.

```D
struct Field(T, string NAME) {
	string name = NAME;	
	T value;
}

alias StaticField = Field;

struct Method(RET, string NAME, ARGS...) {
	static if (!is(RET == void))
		RET returnValue;
	
	string name = NAME;
	ARGS args;	
}

alias StaticMethod = Method;

mixin template JavaClass(VALUES...) {
		pragma(msg, VALUES);
}

mixin JavaClass!(
	Field!(int, "x"),
	StaticField!(double, "y"),
	Method!(void, "hello", string),
	StaticMethod!(void, "goodbye")
);
```
Output:
(Field!(int, "x"), StaticField!(double, "y"), Method!(void, "hello", string), StaticMethod!(void, "goodbye"))

**Comment by rikkimax** [comment]
Right now from within a shared library don't attempt to use std.stdio specifically stdout.writeln.
Its dying quite magnificently.

**Comment by jamesmahler** [comment]
If you are loading from not D... You have to initialize D environment
first.  I don't remember the call... It's on the forums.

I was too busy tonight, but I will look over pull request probably tomorrow.

James

**Comment by rikkimax** [comment]
I'm aware of that.
That gets e.g. std.file working but not std.stdio.

**Comment by rikkimax** [comment]
Manually getting stdin/stdout/stderr from WinAPI and setting them into std.stdio.
Everything there should just work now.
However supposedly a friend has said it might because CRT is not being initiated. Either way, I haven't been able to get that to work.

**Comment by jamesmahler** [comment]
This doesn't seem to work for me... the unit tests no long run and exit with error code 11.  I reverted it for now.

```
Running ./bin/djvm_test 
./bin/djvm_test(_D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPS4core3sys5posix6signal9siginfo_tPvZv+0x3e)[0x4afb56]
Error executing command test: Program exited with code -11
```

There are some random small things:
* updating README.md with dub instructions for getting started
* You missed adding to copyright and authors in dub.json
* Is there any reason the top level project doesn't depend on the sub projects so they build when you just type dub?

I will try to keep other changes to a minimum while we work out what's going on so it's not too bad to merge back in.

**Comment by rikkimax** [comment]
I'm not in a position to do much for the next day or so.
But in djvm.wrappers.jvm look at prepare method.
Remove the optional calling of DerelictJvm.load.

From there, you will need to debug what the location to your jvm.so is.
This is a distro level thing. It currently doesn't support 32bit.

I have the code to create instances of classes right now.
I want to have method calling working before this gets pulled.
Right now java.lang.String .charAt is callable, but its hard coded mostly. The code for all this is not on github.

Sorry I can't debug this for you.

**Comment by rikkimax** [comment]
Another thing, make sure you are building for 64bit.
Try the shared library version. If that works fine its definately not loading the JNI functions from the jvm shared library. Instructions is in a README of the subpackage.

**Comment by jamesmahler** [comment]
Both machines are on 64-bit.

I'm not sure how this worked for you on mint.  You must be using a different JVM.

```
/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar]
/lib/amd64/server/libjvm.so
```

That is the string it's trying to use.  There is still a new line in it.  Also "/rt.jar]" probably needs to be stripped.

What does your output of java -verbose -version look like?  Mine ends with

```
[Loaded java.lang.Shutdown$Lock from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar]
```

I'm not sure how standard that is across JVMs.  I'm using open jdk 7.  The output seems to look different on j3 and j9 also.

When not using the derelic stuff, if I have LD_LIBRARY_PATH set it just works.

For the dereleic stuff... would it be possible to first try to just load the name (letting LD_LIBRARY_PATH or whatever equivalent kick in) ... then if that doesn't work... it would probably be better to have a fallback of directories that are based on $JAVA_HOME... ["./amd64/server/", "whereEverWindowsIs"].

I haven't had time to go through how the derelic library loading stuff works.  I barely got through this before my kid came in and needed stuff.

**Comment by rikkimax** [comment]
``[Loaded java.lang.Shutdown$Lock from C:\Program Files\Java\jre1.8.0_20\lib\rt.jar]``
Thats my last line.

Its now able to grab path via ``C:\Program Files (x86)\Java\jre7\lib\rt.jar``.

Why did I go this way for detecting location?

JAVA_HOME isn't always set, especially on non JDK installed machines.
LD_LIBRARY_PATH is posix only.

Also the updated prepare method hasn't been tested in any form for 32bit. And only on a 64bit JRE/JDK install on windows.
Theres a bunch of TODO's in the code for what needs to be done in this reguard.

Derelict-Util can find most dll's on e.g. PATH variables and such. But hunting down java's dll won't be that easy.
I've changed the prepare method to try Derelict's loader first because it should just work.
If you feel long term that my code to manually grab its location isn't worth keeping. Well not hard to remove.

**Comment by rikkimax** [comment]
Ehh its not auto updating commits now. You may need to enable it.

**Comment by rikkimax** [comment]
In total I expect 3 pull requests will be needed for what I have in store.
This is just getting majority of code reworked based upon how you did it.
Second is getting the calling of java.
Lastly major clean up.

If I feel like it, after that then I'll get java calling D working.
It shouldn't be too hard.
But if we have it, we will probably have better support to communicate with java then luad does with lua.

**Comment by jamesmahler** [comment]
I opened a gitter.im chat room so we can stop talking on a closed pull reqeust.

**Pull request merged**
